#!/bin/bash
echo "Stopping KubePulse AI Python processes and port forwards..."
pkill -f "collectors/normalizer.py"
pkill -f "agents.cpu_worker"
pkill -f "agents.memory_worker"
pkill -f "agents.storage_worker"
pkill -f "agents.log_worker"
pkill -f "correlation.correlation_processor"
pkill -f "correlation.db_writer"
pkill -f "nlp.incident_intelligence"
pkill -f "api.main"
pkill -f "uvicorn"
pkill -f "port-forward"
echo "KubePulse AI background services stopped."
